<a href="https://colab.research.google.com/github/Deepak-tailor/Data-Analysis/blob/main/numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [41]:
import numpy as np

In [42]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [43]:
a.shape

(3, 4)

In [44]:
a[2][3]

np.int64(12)

In [45]:
a[2,3]# same as a[2][3]

np.int64(12)

In [46]:
a[-1, -1] #same as a[-1][-1]

np.int64(12)

In [47]:
#getting data corresponding to multiple indices in a 2d array

In [48]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [49]:
a[1, 2]

np.int64(7)

In [50]:
a[[1,2], [2, 1]] #same as a[1][2], a[2][1]

array([ 7, 10])

In [51]:
a[[2, 1, 1], [1, 0, 2]]

array([10,  5,  7])

Slicing in 2d array

In [55]:
arr = np.arange(12)

In [56]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [57]:
arr[:5]

array([0, 1, 2, 3, 4])

In [58]:
arr[0:5:1]

array([0, 1, 2, 3, 4])

In [59]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [60]:
a[:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [61]:
a[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [62]:
a[1:3]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
a1 =np.arange(0 ,16).reshape(4,4)

In [29]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [30]:
a1[ : , 0:2]

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [31]:
a1[ : , :2]

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [32]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [33]:
a1[1:,1:]

array([[ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [34]:
a1


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [37]:
a1[1:3, 1:4]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [38]:
a1.diagonal()

array([ 0,  5, 10, 15])

In [39]:
a1[1:2, 1:3]

array([[5, 6]])

In [63]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [64]:
a1[[0,1,2,3], [0,1,2,3]]

array([ 0,  5, 10, 15])

In [65]:
#Using jump/step in slicing

In [66]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [67]:
arr[::2]

array([ 0,  2,  4,  6,  8, 10])

In [68]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [69]:
a1[ : , 1::2]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15]])

In [70]:
# Fancy indexing

In [72]:
a1[ : , [1,3]]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15]])

Masking of value in an Array

In [73]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [74]:
#Get all the values which are > 6

In [75]:
for i in a:
  for j in i:
    if j > 6:
      print(j)

7
8
9
10
11
12


In [76]:
3 > 6

False

In [77]:
a > 6 # Boolean Array

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [78]:
a[a>6]

array([ 7,  8,  9, 10, 11, 12])

In [79]:
b = a[1>6]

In [80]:
b # Masked array with a > 6

array([], shape=(0, 3, 4), dtype=int64)

In [81]:
# Hw: Try masking using 1d array as well

In [132]:
arr_masked = arr[arr > 5]
display(arr_masked)

array([10, 20, 30, 40])

Vectoriazation

In [82]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [83]:
for i in arr:
  print(i + 1)

1
2
3
4
5
6
7
8
9
10
11
12


In [84]:
def random_function(x):
  if x % 2 == 0:
    x += 2
  else:
    x -= 2
  return x

In [85]:
arr * 2 # Element wise operations, efficient due to parallel processing

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [86]:
# random-function(arr)

In [87]:
for i in arr:
  print(random_function(i))

2
-1
4
1
6
3
8
5
10
7
12
9


In [ ]:
np.vectorized

Aggregate Function

In [88]:
a


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [89]:
# SCAMM -> Sum, Count, Avg, MIn, Max

In [90]:
a.size

12

In [92]:
a.sum()

np.int64(78)

In [93]:
a.max()

np.int64(12)

In [94]:
a.mean()

np.float64(6.5)

In [95]:
a.min()

np.int64(1)

In [96]:
a.sum(axis =1) # wrt rows -> horizontal axis

array([10, 26, 42])

In [97]:
a.sum(axis = 0) # wrt column -> Vertical axis

array([15, 18, 21, 24])

In [98]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [99]:
a.max()

np.int64(12)

In [100]:
a.max(axis = 1)

array([ 4,  8, 12])

In [101]:
a[0].max()

np.int64(4)

In [102]:
a[1].max()

np.int64(8)

Logical Operators


*   any
*   all



In [103]:
# any : will give True in O/P even if single value satisfies the condition
# all : will give True in O/P if every value satisfied the condition

In [104]:
# any -> or
# all -> and

In [105]:
# heights = 176, 172, 162, 154, 166

# a => 175 greater than any of the student => Yes
# a => 175 greater than all of the student -> No


In [106]:
# Price of items in your shopping list

In [134]:
Prices = np.array([50, 45, 25, 20, 35])

# Your budget
budget = 30
# check if there's atleast one item that you can afford?
can_afford = (Prices <= budget).any()

if can_afford:
  print("You can afford atleast one item")
else:
  print("You can't afford atleast one item")

You can afford atleast one item


In [108]:
# np.where

In [112]:
# product prices
prices = np.array([45, 55, 60, 75, 40, 90])

# Apply a 10% discount on product having prices above $50
discounted_prices = np.where(prices > 50, prices * 0.9, prices)

print(discounted_prices)

[45.  49.5 54.  67.5 40.  81. ]


In [110]:
prices > 50

array([False,  True,  True,  True, False,  True])

In [111]:
np.where(prices > 50)

(array([1, 2, 3, 5]),)

In [113]:
False == 0

True

In [114]:
# quize
arr = np.array([-3,4,27,34,-2,0, -45,-11,4,0])
print(np.where(arr))

(array([0, 1, 2, 3, 4, 6, 7, 8]),)


In [116]:
#quize
arr = np.array([10,20,30,40])
arr > 25

array([False, False,  True,  True])

Sorting

In [117]:
a = np.array([4,7,0,3,8,2,5,1,6,9])
a

array([4, 7, 0, 3, 8, 2, 5, 1, 6, 9])

In [ ]:
#np.sort(array) -> sorts the values in ascending order and return a copy of the array.

In [118]:
np.sort(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [119]:
a

array([4, 7, 0, 3, 8, 2, 5, 1, 6, 9])

In [121]:
# arr.sort() -> sorts the array in place.


In [122]:
a.sort()

In [123]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
sort the array in descending order

In [133]:
a[::-1]

array([[40, 20, 30],
       [ 2,  0,  7],
       [ 1,  5,  3]])

In [125]:
#sorting in a 2d array
a = np.array([[1,5,3],[2,0,7],[40,20,30]])

In [126]:
a

array([[ 1,  5,  3],
       [ 2,  0,  7],
       [40, 20, 30]])

In [127]:
np.sort(a)

array([[ 1,  3,  5],
       [ 0,  2,  7],
       [20, 30, 40]])

In [128]:
np.sort(a, axis = 1)

array([[ 1,  3,  5],
       [ 0,  2,  7],
       [20, 30, 40]])

In [130]:
np.sort(a, axis = 0)

array([[ 1,  0,  3],
       [ 2,  5,  7],
       [40, 20, 30]])

In [131]:
np.sort(a[1])

array([0, 2, 7])